---
- name:              ====== DELETE YANDEX ======
  hosts:             ws-c01-{{ host }}
  vars_prompt:
    - name:          host
      prompt:        "Introducei grup/host"
      private:       no
#    - name:         ext
#      prompt:       "Introducei extensia"
#      private:      no

  tasks:
#   - name:          Delete APP
#     win_package:
#      path:         \\ws-c01-22\c$\Users\renat.calancea\AppData\Local\Yandex\YandexBrowser\Application\19.9.0.1343\Installer\1setup.exe
#      product_id:   '{4D922459-6A2E-4E43-B7A1-86872A9078F3}'
#      state:        absent
#     register:      result

#   - debug:
#      var:          result


#   - name:          ====== DELETE YANDEX ======
#     win_shell:     C:\Users\{{ item }}\AppData\Local\Yandex\YandexBrowser\Application\19.9.3.314\Installer\setup.exe --uninstall --force-uninstall
#     loop:
#       - "renat.calancea"
    - name:          ====== show DIR ======
      win_shell:     dir
      args:
        chdir:       \\ws-c01-{{ host }}\c$\Users\{{ item }}\Downloads
      loop:

      register:      dirs
      ignore_errors: yes
#      when:         '"exe" in variable1'

    - debug:
       var:          dirs
